apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: tabpy
        image: {{ .Values.image}}:{{ .Values.tag }}
        ports:
        - containerPort: {{ .Values.port }}
        envFrom:
          - secretRef:
              name: {{ .Chart.Name }}