apiVersion: v1
kind: Service
metadata: 
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
  namespace: {{.Release.Namespace}}
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - protocol: TCP
      port: {{.Values.port}}
      targetPort: {{ .Values.port }}
      name: http-{{ .Chart.Name }}
  type: NodePort 